name: CI
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server
    env:
      NODE_ENV: test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: server/package-lock.json
      - name: Create .env file
        run: |
          echo "DATABASE_URL=file:./prisma/ci.db" >> .env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
          echo "PORT=3000" >> .env
          echo "PUBLIC_SQUARE_ADMIN_ID=test-admin-id" >> .env
          echo "BCRYPT_ROUNDS=1" >> .env
      - run: npm ci
      - run: npx prisma generate
      - run: npx prisma db push --force-reset
      - run: npm test -- --pool=forks --poolOptions.forks.singleFork=true

